In [1]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [5]:
games=pd.read_csv(r'C:\Users\hp\Data Analyst\csv\Online_game.csv')

In [7]:
games

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

### Description

* This dataset appears to represent video game sales data, containing information about 16,598 video games. 
* Each row corresponds to a specific video game, and the dataset includes the following columns   * Rank: A unique integer identifier that ranks the video games based on a specific criterion (likely sales    * Name: The name of the video ga
    * Platform: The gaming platform on which the video game was released (e.g., PS4, Xbox One, 
    * Year: The ye game was released. This column has some missing values, with 16,327 non-null entries out of 16,598.
    * Genre: The genre of the video game (e.g., Action, Sports, RPG).
    * Publisher: The company that published the video game. There are a few missing values, with 16,540 non-null entries.
    * NA_Sales: Sales in North America, measured in millions of units.
    * EU_Sales: Sales in Europe, measured in millions of units.
    * JP_Sales: Sales in Japan, measured in millions of units.
    *
Other_Sales: Sales in regions other than North America, Europe, and Japan, measured in millions of units.
    * Global_Sales: The total global sales of the video game, measured in millions of units.ar the

In [17]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [20]:
games.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [26]:
games.fillna(0,inplace=True)

In [28]:
games.isnull().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

In [32]:
games.duplicated().sum()

0

In [34]:
games.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,1973.647307,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,254.346809,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [36]:
games.describe().T

,count,mean,std,min,25%,50%,75%,max
Rank,16598.0,8300.605254,4791.853933,1.00,4151.25,8300.50,12449.75,16600.00
Year,16598.0,1973.647307,254.346809,0.00,2003.00,2007.00,2010.00,2020.00
NA_Sales,16598.0,0.264667,0.816683,0.00,0.00,0.08,0.24,41.49
EU_Sales,16598.0,0.146652,0.505351,0.00,0.00,0.02,0.11,29.02
JP_Sales,16598.0,0.077782,0.309291,0.00,0.00,0.00,0.04,10.22
Other_Sales,16598.0,0.048063,0.188588,0.00,0.00,0.01,0.04,10.57
Global_Sales,16598.0,0.537441,1.555028,0.01,0.06,0.17,0.47,82.74

In [38]:
games

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [46]:
games['Publisher'].unique()

array(['Nintendo', 'Microsoft Game Studios', 'Take-Two Interactive',
       'Sony Computer Entertainment', 'Activision', 'Ubisoft',
       'Bethesda Softworks', 'Electronic Arts', 'Sega', 'SquareSoft',
       'Atari', '505 Games', 'Capcom', 'GT Interactive',
       'Konami Digital Entertainment',
       'Sony Computer Entertainment Europe', 'Square Enix', 'LucasArts',
       'Virgin Interactive', 'Warner Bros. Interactive Entertainment',
       'Universal Interactive', 'Eidos Interactive', 'RedOctane',
       'Vivendi Games', 'Enix Corporation', 'Namco Bandai Games',
       'Palcom', 'Hasbro Interactive', 'THQ', 'Fox Interactive',
       'Acclaim Entertainment', 'MTV Games', 'Disney Interactive Studios',
       0, 'Majesco Entertainment', 'Codemasters', 'Red Orb', 'Level 5',
       'Arena Entertainment', 'Midway Games', 'JVC', 'Deep Silver',
       '989 Studios', 'NCSoft', 'UEP Systems', 'Parker Bros.', 'Maxis',
       'Imagic', 'Tecmo Koei', 'Valve Software', 'ASCII Entertainment',
       'Mindscape', 'Infogrames', 'Unknown', 'Square', 'Valve',
       'Activision Value', 'Banpresto', 'D3Publisher',
       'Oxygen Interactive', 'Red Storm Entertainment', 'Video System',
       'Hello Games', 'Global Star', 'Gotham Games', 'Westwood Studios',
       'GungHo', 'Crave Entertainment', 'Hudson Soft', 'Coleco',
       'Rising Star Games', 'Atlus', 'TDK Mediactive', 'ASC Games',
       'Zoo Games', 'Accolade', 'Sony Online Entertainment', '3DO', 'RTL',
       'Natsume', 'Focus Home Interactive', 'Alchemist',
       'Black Label Games', 'SouthPeak Games', 'Mastertronic', 'Ocean',
       'Zoo Digital Publishing', 'Psygnosis', 'City Interactive',
       'Empire Interactive', 'Success', 'Compile', 'Russel', 'Taito',
       'Agetec', 'GSP', 'Microprose', 'Play It', 'Slightly Mad Studios',
       'Tomy Corporation', 'Sammy Corporation', 'Koch Media',
       'Game Factory', 'Titus', 'Marvelous Entertainment', 'Genki',
       'Mojang', 'Pinnacle', 'CTO SpA', 'TalonSoft', 'Crystal Dynamics',
       'SCi', 'Quelle', 'mixi, Inc', 'Rage Software', 'Ubisoft Annecy',
       'Scholastic Inc.', 'Interplay', 'Mystique', 'ChunSoft',
       'Square EA', '20th Century Fox Video Games', 'Avanquest Software',
       'Hudson Entertainment', 'Nordic Games', 'Men-A-Vision', 'Nobilis',
       'Big Ben Interactive', 'Touchstone', 'Spike', 'Jester Interactive',
       'Nippon Ichi Software', 'LEGO Media', 'Quest',
       'Illusion Softworks', 'Tigervision', 'Funbox Media',
       'Rocket Company', 'Metro 3D', 'Mattel Interactive', 'IE Institute',
       'Rondomedia', 'Sony Computer Entertainment America',
       'Universal Gamex', 'Ghostlight', 'Wizard Video Games',
       'BMG Interactive Entertainment', 'PQube', 'Trion Worlds', 'Laguna',
       'Ignition Entertainment', 'Takara', 'Kadokawa Shoten', 'Destineer',
       'Enterbrain', 'Xseed Games', 'Imagineer',
       'System 3 Arcade Software', 'CPG Products', 'Aruze Corp',
       'Gamebridge', 'Midas Interactive Entertainment', 'Jaleco',
       'Answer Software', 'XS Games', 'Activision Blizzard',
       'Pack In Soft', 'Rebellion', 'Xplosiv', 'Ultravision',
       'GameMill Entertainment', 'Wanadoo', 'NovaLogic', 'Telltale Games',
       'Epoch', 'BAM! Entertainment', 'Knowledge Adventure', 'Mastiff',
       'Tetris Online', 'Harmonix Music Systems', 'ESP', 'TYO',
       'Telegames', 'Mud Duck Productions', 'Screenlife', 'Pioneer LDC',
       'Magical Company', 'Mentor Interactive', 'Kemco',
       'Human Entertainment', 'Avanquest', 'Data Age',
       'Electronic Arts Victor', 'Black Bean Games', 'Jack of All Games',
       '989 Sports', 'Takara Tomy', 'Media Rings', 'Elf', 'Kalypso Media',
       'Starfish', 'Zushi Games', 'Jorudan', 'Destination Software, Inc',
       'New', 'Brash Entertainment', 'ITT Family Games', 'PopCap Games',
       'Home Entertainment Suppliers', 'Ackkstudios', 'Starpath Corp.',
       'P2 Games', 'BPS', 'Gathering of Developers', 'NewKidCo',
       'Storm City Games', 'CokeM Interactive', 'CBS Electronics',
       'Magix', 'Marvelous Interactive', 'Nihon Falcom Corporation',
       'Wargaming.net', 'Angel Studios', 'Arc System Works', 'Playmates',
       'SNK Playmore', 'Hamster Corporation', 'From Software',
       'Nippon Columbia', 'Nichibutsu', 'Little Orbit',
       'Conspiracy Entertainment', 'DTP Entertainment', 'Hect',
       'Mumbo Jumbo', 'Pacific Century Cyber Works', 'Indie Games',
       'Liquid Games', 'NEC', 'Axela', 'ArtDink', 'Sunsoft', 'Gust',
       'SNK', 'NEC Interchannel', 'FuRyu', 'Xing Entertainment',
       'ValuSoft', 'Victor Interactive', 'Detn8 Games',
       'American Softworks', 'Nordcurrent', 'Bomb', 'Falcom Corporation',
       'AQ Interactive', 'CCP', 'Milestone S.r.l.', 'Sears',
       'JoWood Productions', 'Seta Corporation', 'On Demand', 'NCS',
       'Aspyr', 'Gremlin Interactive Ltd', 'Agatsuma Entertainment',
       'Compile Heart', 'Culture Brain', 'Mad Catz', 'Shogakukan',
       'Merscom LLC', 'Rebellion Developments', 'Nippon Telenet',
       'TDK Core', 'bitComposer Games', 'Foreign Media Games', 'Astragon',
       'SSI', 'Kadokawa Games', 'Idea Factory',
       'Performance Designed Products', 'Asylum Entertainment',
       'Core Design Ltd.', 'PlayV', 'UFO Interactive',
       'Idea Factory International', 'Playlogic Game Factory',
       'Essential Games', 'Adeline Software', 'Funcom',
       'Panther Software', 'Blast! Entertainment Ltd', 'Game Life',
       'DSI Games', 'Avalon Interactive', 'Popcorn Arcade',
       'Neko Entertainment', 'Vir2L Studios', 'Aques', 'Syscom',
       'White Park Bay Software', 'System 3', 'Vatical Entertainment',
       'Daedalic', 'EA Games', 'Media Factory', 'Vic Tokai',
       'The Adventure Company', 'Game Arts', 'Broccoli', 'Acquire',
       'General Entertainment', 'Excalibur Publishing', 'Imadio',
       'Swing! Entertainment', 'Sony Music Entertainment', 'Aqua Plus',
       'Paradox Interactive', 'Hip Interactive',
       'DreamCatcher Interactive', 'Tripwire Interactive', 'Sting',
       'Yacht Club Games', 'SCS Software', 'Bigben Interactive',
       'Havas Interactive', 'Slitherine Software', 'Graffiti', 'Funsta',
       'Telstar', 'U.S. Gold', 'DreamWorks Interactive',
       'Data Design Interactive', 'MTO', 'DHM Interactive', 'FunSoft',
       'SPS', 'Bohemia Interactive', 'Reef Entertainment',
       'Tru Blu Entertainment', 'Moss', 'T&E Soft', 'O-Games',
       'Aksys Games', 'NDA Productions', 'Data East',
       'Time Warner Interactive', 'Gainax Network Systems', 'Daito',
       'O3 Entertainment', 'Gameloft', 'Xicat Interactive',
       'Simon & Schuster Interactive', 'Valcon Games', 'PopTop Software',
       'TOHO', 'HMH Interactive', '5pb', 'Cave',
       'CDV Software Entertainment', 'Microids', 'PM Studios', 'Paon',
       'Micro Cabin', 'GameTek', 'Benesse', 'Type-Moon',
       'Enjoy Gaming ltd.', 'Asmik Corp', 'Interplay Productions',
       'Asmik Ace Entertainment', 'inXile Entertainment', 'Image Epoch',
       'Phantom EFX', 'Evolved Games', 'responDESIGN',
       'Culture Publishers', 'Griffin International', 'Hackberry',
       'Hearty Robin', 'Nippon Amuse', 'Origin Systems', 'Seventh Chord',
       'Mitsui', 'Milestone', 'Abylight', 'Flight-Plan', 'Glams', 'Locus',
       'Warp', 'Daedalic Entertainment', 'Alternative Software',
       'Myelin Media', 'Mercury Games', 'Irem Software Engineering',
       'Sunrise Interactive', 'Elite', 'Evolution Games', 'Tivola',
       'Global A Entertainment', 'Edia', 'Athena', 'Aria', 'Gamecock',
       'Tommo', 'Altron', 'Happinet', 'iWin', 'Media Works', 'Fortyfive',
       'Revolution Software', 'Imax', 'Crimson Cow', '10TACLE Studios',
       'Groove Games', 'Pack-In-Video', 'Insomniac Games',
       'Ascaron Entertainment GmbH', 'Asgard', 'Ecole', 'Yumedia',
       'Phenomedia', 'HAL Laboratory', 'Grand Prix Games', 'DigiCube',
       'Creative Core', 'Kaga Create', 'WayForward Technologies',
       'LSP Games', 'ASCII Media Works', 'Coconuts Japan', 'Arika',
       'Ertain', 'Marvel Entertainment', 'Prototype',
       'TopWare Interactive', 'Phantagram', '1C Company',
       'The Learning Company', 'TechnoSoft', 'Vap', 'Misawa', 'Tradewest',
       'Team17 Software', 'Yeti', 'Pow', 'Navarre Corp', 'MediaQuest',
       'Max Five', 'Comfort', 'Monte Christo Multimedia', 'Pony Canyon',
       'Riverhillsoft', 'Summitsoft', 'Milestone S.r.l', 'Playmore',
       'MLB.com', 'Kool Kizz', 'Flashpoint Games', '49Games',
       'Legacy Interactive', 'Alawar Entertainment', 'CyberFront',
       'Cloud Imperium Games Corporation', 'Societa',
       'Virtual Play Games', 'Interchannel', 'Sonnet', 'Experience Inc.',
       'Zenrin', 'Iceberg Interactive', 'Ivolgamus', '2D Boy',
       'MC2 Entertainment', 'Kando Games', 'Just Flight', 'Office Create',
       'Mamba Games', 'Fields', 'Princess Soft', 'Maximum Family Games',
       'Berkeley', 'Fuji', 'Dusenberry Martin Racing', 'imageepoch Inc.',
       'Big Fish Games', 'Her Interactive', 'Kamui', 'ASK',
       'Headup Games', 'KSS', 'Cygames', 'KID', 'Quinrose', 'Sunflowers',
       'dramatic create', 'TGL', 'Encore', 'Extreme Entertainment Group',
       'Intergrow', 'G.Rev', 'Sweets', 'Kokopeli Digital Studios',
       'Number None', 'Nexon', 'id Software', 'BushiRoad', 'Tryfirst',
       'Strategy First', '7G//AMES', 'GN Software', "Yuke's",
       'Easy Interactive', 'Licensed 4U', 'FuRyu Corporation',
       'Lexicon Entertainment', 'Paon Corporation', 'Kids Station', 'GOA',
       'Graphsim Entertainment', 'King Records', 'Introversion Software',
       'Minato Station', 'Devolver Digital', 'Blue Byte', 'Gaga',
       'Yamasa Entertainment', 'Plenty', 'Views', 'fonfun', 'NetRevo',
       'Codemasters Online', 'Quintet', 'Phoenix Games', 'Dorart',
       'Marvelous Games', 'Focus Multimedia', 'Imageworks',
       'Karin Entertainment', 'Aerosoft', 'Technos Japan Corporation',
       'Gakken', 'Mirai Shounen', 'Datam Polystar', 'Saurus', 'HuneX',
       'Revolution (Japan)', 'Giza10', 'Visco', 'Alvion', 'Mycom', 'Giga',
       'Warashi', 'System Soft', 'Sold Out', 'Lighthouse Interactive',
       'Masque Publishing', 'RED Entertainment', 'Michaelsoft',
       'Media Entertainment', 'New World Computing', 'Genterprise',
       'Interworks Unlimited, Inc.', 'Boost On', 'Stainless Games',
       'EON Digital Entertainment', 'Epic Games', 'Naxat Soft',
       'Ascaron Entertainment', 'Piacci', 'Nitroplus',
       'Paradox Development', 'Otomate', 'Ongakukan', 'Commseed',
       'Inti Creates', 'Takuyo', 'Interchannel-Holon', 'Rain Games',
       'UIG Entertainment'], dtype=object)

## -Q1Retrieve the details of nintendo publishers

In [60]:
nint=games[games['Publisher']=='Nintendo']
nint

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16269,16272,Slide Adventure: Mag Kid,DS,2007.0,Action,Nintendo,0.00,0.00,0.01,0.00,0.01
16357,16360,Mario vs. Donkey Kong: Tipping Stars,WiiU,2015.0,Puzzle,Nintendo,0.00,0.00,0.01,0.00,0.01
16456,16459,Art Academy: Home Studio,WiiU,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01
16473,16476,Captain Rainbow,Wii,2008.0,Adventure,Nintendo,0.00,0.00,0.01,0.00,0.01
16542,16545,Mario & Luigi: Paper Jam & Mario Kart 7 Double...,3DS,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01

In [86]:
games[games['Publisher'(games['Global_Sales'].max())

SyntaxError: incomplete input (1727968879.py, line 1)

## -Q2retrieve the games that is developed by nintendo

In [62]:
nint['Name'].unique()

array(['Wii Sports', 'Super Mario Bros.', 'Mario Kart Wii',
       'Wii Sports Resort', 'Pokemon Red/Pokemon Blue', 'Tetris',
       'New Super Mario Bros.', 'Wii Play', 'New Super Mario Bros. Wii',
       'Duck Hunt', 'Nintendogs', 'Mario Kart DS',
       'Pokemon Gold/Pokemon Silver', 'Wii Fit', 'Wii Fit Plus',
       'Super Mario World',
       'Brain Age: Train Your Brain in Minutes a Day',
       'Pokemon Diamond/Pokemon Pearl', 'Super Mario Land',
       'Super Mario Bros. 3', 'Pokemon Ruby/Pokemon Sapphire',
       'Pokemon Black/Pokemon White',
       'Brain Age 2: More Training in Minutes a Day',
       'PokÃ©mon Yellow: Special Pikachu Edition', 'Pokemon X/Pokemon Y',
       'Super Smash Bros. Brawl', 'Animal Crossing: Wild World',
       'Mario Kart 7', 'Pokemon HeartGold/Pokemon SoulSilver',
       'Super Mario 64', 'Super Mario Galaxy',
       'Pokemon Omega Ruby/Pokemon Alpha Sapphire',
       'Super Mario Land 2: 6 Golden Coins', 'Super Mario 3D Land',
       'Super Mario All-Stars', 'Pokemon FireRed/Pokemon LeafGreen',
       'Mario Kart 64', 'New Super Mario Bros. 2', 'Donkey Kong Country',
       'Animal Crossing: New Leaf', 'Mario Party DS', 'Super Mario Kart',
       'Wii Party', 'Mario Party 8', 'Pokemon Black 2/Pokemon White 2',
       'GoldenEye 007', 'PokÃ©mon Platinum Version',
       'Super Mario Galaxy 2', 'The Legend of Zelda: Ocarina of Time',
       'Super Mario Bros. 2', 'Super Smash Bros. for Wii U and 3DS',
       'The Legend of Zelda: Twilight Princess',
       'Super Smash Bros. Melee', 'Mario Kart 8',
       'Mario Kart: Double Dash!!', 'Big Brain Academy',
       'Donkey Kong Country Returns', 'The Legend of Zelda',
       'PokÃ©mon Emerald Version', 'PokÃ©mon Crystal Version',
       'Super Mario Sunshine',
       'Dragon Quest IX: Sentinels of the Starry Skies',
       'Super Smash Bros.', 'Super Mario Advance',
       'Mario Kart: Super Circuit', 'Pokemon Stadium', 'Dr. Mario',
       'Pokemon Pinball', 'Donkey Kong 64',
       'Professor Layton and the Curious Village',
       'New Super Mario Bros. U', 'Super Mario Land 3: Wario Land',
       'The Legend of Zelda: Phantom Hourglass',
       "Donkey Kong Country 2: Diddy's Kong Quest", 'Tomodachi Life',
       "Kirby's Dream Land", "Link's Crossbow Training",
       'Pokemon Mystery Dungeon: Explorers of Time/Explorers of Darkness',
       'Diddy Kong Racing', 'Animal Crossing: City Folk',
       'The Legend of Zelda: A Link to the Past',
       'The Legend of Zelda: The Wind Waker',
       "Luigi's Mansion: Dark Moon", 'Splatoon', 'Nintendo Land',
       'Zelda II: The Adventure of Link', 'Super Mario 3D World',
       'Excitebike', "Super Mario World 2: Yoshi's Island",
       'The Legend of Zelda: Skyward Sword', 'Star Fox 64', 'Golf',
       'Professor Layton and the Diabolical Box', 'Donkey Kong Land',
       'Monster Hunter 4 Ultimate',
       'Flash Focus: Vision Training in Minutes a Day',
       "The Legend of Zelda: Link's Awakening",
       "Mario & Luigi: Bowser's Inside Story",
       'Big Brain Academy: Wii Degree', 'Nintendogs + cats',
       'Super Paper Mario', 'PokÃ©mon Trading Card Game',
       'Friend Collection', 'Banjo-Kazooie', 'Pokemon Snap',
       "Luigi's Mansion",
       "Donkey Kong Country 3: Dixie Kong's Double Trouble!", 'Kung Fu',
       'Clubhouse Games', 'F-1 Race',
       'The Legend of Zelda: Spirit Tracks',
       "The Legend of Zelda: Majora's Mask",
       'Professor Layton and the Unwound Future',
       'English Training: Have Fun Improving Your Skills!',
       'Mario Party 9', 'Wii Music', 'Yokai Watch 2 Ganso/Honke',
       'Baseball', 'Killer Instinct', 'Super Mario Maker',
       'Rhythm Heaven', 'Animal Crossing', 'Star Wars Episode I Racer',
       'Personal Trainer: Cooking',
       'The Legend of Zelda: A Link Between Worlds', 'Donkey Kong',
       "Mike Tyson's Punch-Out!!", 'Star Fox',
       'Animal Crossing: Happy Home Designer', 'Kirby Super Star Ultra',
       'Wave Race 64', 'WarioWare: Smooth Moves', 'F-Zero',
       "Yoshi's Story", 'Metroid Prime', "Yoshi's Island DS",
       'Professor Layton and the Last Specter', 'Monster Hunter Tri',
       'Mario Paint', 'PokÃ©mon Stadium 2', 'Metroid', 'Mario Party',
       'Mario vs. Donkey Kong: Mini-Land Mayhem!',
       'Super Mario Bros.: The Lost Levels',
       'Star Wars: Shadows of the Empire', 'Mario Strikers Charged',
       'Style Savvy', 'Super Mario All-Stars: Limited Edition',
       'Art Academy', 'PokÃ©mon Colosseum', 'Perfect Dark',
       'Mario Party 2', 'Mario Party 4', 'Ice Hockey', 'Pro Wrestling',
       "Kirby's Dream Land 2", 'Donkey Kong Land II',
       "The Legend of Zelda: Majora's Mask 3D", 'Mario Tennis',
       'WarioWare Touched!', 'Pokemon Ranger: Shadows of Almia',
       'Mario Bros.', 'Paper Mario: Sticker Star',
       'Kirby: Nightmare in Dream Land', 'Wario Land 4',
       'Paper Mario: The Thousand-Year Door', 'New Super Luigi U',
       "The Legend of Zelda: Link's Awakening DX", 'Wario Land 3',
       "Kirby's Pinball Land", 'Pokemon Ranger',
       'Mario & Luigi: Superstar Saga', 'Star Wars: Rogue Squadron',
       'Tennis', 'Volleyball',
       'Super Mario RPG: Legend of the Seven Stars', 'Mahjong',
       'R.C. Pro-Am', 'Tetris DS', "Kirby's Epic Yarn",
       'Mario Sports Mix', 'Mario Party 5',
       'Pokemon Mystery Dungeon: Red/Blue Rescue Team',
       'Mario & Luigi: Dream Team',
       'PokÃ©mon Mystery Dungeon: Blue Rescue Team',
       '1080Â°: TenEighty Snowboarding', 'Fire Emblem: Awakening',
       'Super Street Fighter II', 'SimCity', 'Rad Racer', 'Soccer',
       'Kirby Squeak Squad', 'Alleyway', 'Tetris DX',
       'Mario Super Sluggers', 'The Legend of Zelda: Oracle of Ages',
       'Mario Party 3', 'Yokai Watch', 'Star Fox Adventures',
       'The Legend of Zelda: Oracle of Seasons',
       'Mario Party: Island Tour', 'Pinball', 'Hey You, Pikachu!',
       'Kirby: Triple Deluxe', 'Metroid Prime 3: Corruption',
       'Dragon Quest VI: Realms of Revelation',
       'Professor Layton and the Mask of Miracle', 'Wii Party U',
       'Kirby 64: The Crystal Shards', 'Metroid II: Return of Samus',
       'Golden Sun', 'Kid Icarus', 'Yoshi', "Kirby's Adventure",
       "Cruis'n USA",
       'Kanshuu Nippon Joushikiryoku Kentei Kyoukai: Imasara Hito ni wa Kikenai Otona no Joushikiryoku Training DS',
       'Personal Trainer: Math', "Kirby's Return to Dreamland",
       "Yoshi's Cookie", 'Metroid Fusion', 'Mario Party 6',
       'Super Scope 6', 'Kirby & the Amazing Mirror', 'Pikmin',
       'Mario Hoops 3 on 3', 'Kirby Air Ride',
       'Pokemon Battle Revolution', 'Super Mario Strikers',
       'Pokemon Mystery Dungeon: Explorers of Sky', 'Mario Party 7',
       'Donkey Kong Classics', 'Pokemon Pinball: Ruby & Sapphire',
       'Mario Party 10', 'Fire Emblem Fates',
       'Mario Golf: Toadstool Tour',
       'Donkey Kong Country: Tropical Freeze', 'F1 Race', 'Ice Climber',
       'Final Fantasy: Crystal Chronicles', 'Banjo-Tooie',
       'New Play Control! Mario Power Tennis', 'Nintendo World Cup',
       'Wario Land II', 'Mario Golf', 'Mario Superstar Baseball',
       'LEGO City Undercover', '4 Nin uchi Mahjong', 'Kirby Super Star',
       'Classic NES Series: Super Mario Bros.',
       'The Legend of Zelda: The Minish Cap', 'Super Metroid',
       'Inazuma Eleven 2', 'Metroid: Other M', 'Paper Mario',
       'Bravely Default: Flying Fairy', 'Pocket Monsters Stadium',
       "Yoshi's New Island", 'Mario & Luigi: Partners in Time',
       'Donkey Kong Jungle Beat', 'Metroid Prime 2: Echoes',
       'Pokemon Ranger: Guardian Signs', 'Gyromite',
       "Yoshi's Woolly World", 'Mystery Case Files: MillionHeir',
       'Yakuman', 'Kid Icarus: Uprising',
       'Pokemon Mystery Dungeon: Gates to Infinity', "Hogan's Alley",
       'Hyrule Warriors', 'Pokemon XD: Gale of Darkness',
       'Diddy Kong Racing DS', 'Tetris 2 (All region sales)',
       "Kirby Tilt 'n' Tumble", 'Donkey Kong Country 2',
       'WarioWare, Inc.: Mega MicroGame$', 'Mario Power Tennis',
       'Game & Watch Gallery 2', 'Game & Watch Gallery 3',
       'Golden Sun: The Lost Age', 'Pikmin 2', 'SolarStriker',
       'Mario vs. Donkey Kong 2: March of the Minis',
       "PokÃ©Park Wii: Pikachu's Adventure",
       'Captain Toad: Treasure Tracker', 'Kobe Bryant in NBA Courtside',
       'Final Fantasy I & II: Dawn of Souls',
       'Pokemon Super Mystery Dungeon', 'Wario Land: Shake It!',
       'Mario vs. Donkey Kong', 'Jet Force Gemini', 'Qix', 'Donkey Konga',
       'Pokemon Rumble Blast', 'Pilotwings', 'Super R.C. Pro-Am',
       'Fantasy Life',
       'PokÃ©mon Mystery Dungeon: Red Rescue Team (US weekly sales)',
       'Pilotwings 64', 'Donkey Kong Jr.', 'Pikmin 3',
       'The Legend of Zelda: Tri Force Heroes', 'F-Zero X', 'Popeye',
       'Tales of Symphonia', 'Endless Ocean', 'Star Fox: Assault',
       'Super Princess Peach', 'Pokemon Conquest',
       'Naruto: Clash of Ninja 2', 'F-Zero: Maximum Velocity',
       'Kirby: Mass Attack', 'Donkey Kong Land III', 'Bayonetta 2',
       'Excitebike 64', 'NES Open Tournament Golf',
       'Game & Watch Gallery', 'Xenoblade Chronicles',
       'Mario Party Advance', 'Tetris 2', 'Fire Emblem',
       'PilotWings Resort', 'Wii Play: Motion', 'Star Fox 64 3D',
       'Mario Tennis Open', 'The Legend of Zelda: Twilight Princess HD',
       'Balloon Fight', 'Disney Magical World', 'Fossil Fighters',
       'Classic NES Series: The Legend of Zelda',
       'Fire Emblem: The Sacred Stones',
       'Pokemon Card GB2: Here Comes Team GR!', 'Wii Fit U',
       'Endless Ocean: Blue World', 'The Legendary Starfy',
       'Kirby: Planet Robobot', 'Golden Sun: Dark Dawn',
       'Xenoblade Chronicles X', 'Metroid: Zero Mission', 'Clu Clu Land',
       'Killer Instinct Gold',
       'The Legend of Zelda: Four Swords Adventures', 'EarthBound',
       'Mario & Sonic at the Sochi 2014 Olympic Winter Games',
       "Capcom's Soccer Shootout",
       'Major League Baseball Featuring Ken Griffey Jr',
       'Personal Trainer: Walking', 'PokePark 2: Wonders Beyond',
       'Professor Layton and the Azran Legacy', 'Metroid Prime Hunters',
       'Tetris Party Deluxe', 'Pokemon Dash', 'Donkey Kong Country 3',
       'Jump Ultimate Stars', 'Mario & Luigi: Paper Jam', 'Sword of Mana',
       'Classic NES Series: Donkey Kong', 'Kirby: Canvas Curse',
       'Practise English!', 'Just Dance Wii', 'Style Savvy: Trendsetters',
       'Rhythm Heaven: The Best+', 'Blast Corps',
       'WarioWare, Inc.: Mega Party Game$', 'Advance Wars',
       'Classic NES Series: Zelda II: The Adventure of Link',
       'Fire Emblem: Monsh? no Nazo', 'Mario Pinball Land',
       'Nintendo Presents: New Style Boutique 2 - Fashion Forward',
       "Kirby's Dream Collection: Special Edition", 'The Last Story',
       'Fossil Fighters: Champions', '100 Classic Books',
       'Wario: Master of Disguise', 'New Play Control! Pikmin',
       'F-Zero GX', 'Yoshi Topsy-Turvy',
       'Advance Wars 2: Black Hole Rising', 'Fire Emblem: Shadow Dragon',
       "Cruis'n World", 'Donkey Kong Barrel Blast',
       'Metroid Prime: Trilogy', 'Advance Wars: Days of Ruin',
       "Mario's Picross", 'Ganbaru Watashi no Kakei Diary',
       'New Play Control! Donkey Kong Jungle Beat',
       'Final Fantasy IV Advance', 'Game & Watch Gallery 4',
       'New Play Control! Pikmin 2', 'Wave Race: Blue Storm',
       'WarioWare D.I.Y.', "Mickey's Speedway USA", 'Pokemon Trozei!',
       "Kirby's Dream Course", 'Fire Emblem: Seisen no Keifu',
       'Rooms: The Main Building', 'The Mysterious Murasame Castle',
       'Donkey Kong Jungle Climber', 'Classic NES Series: Dr. Mario',
       'Hotel Dusk: Room 215', 'Hamtaro: Ham-Hams Unite!',
       'DS Bimoji Training', 'Jump Super Stars', 'Excite Truck',
       'Inazuma Eleven', 'Fire Emblem: Path of Radiance',
       'Star Fox Command', 'Inazuma Eleven GO',
       'Kirby and the Rainbow Curse', 'Picross 3D',
       "Wayne Gretzky's 3D Hockey", 'Mario Tennis: Power Tour',
       'Naruto Shippuden: Clash of Ninja Revolution 3',
       'Kenkou Ouen Recipe 1000: DS Kondate Zenshuu', 'Jam With the Band',
       'Fire Emblem: Radiant Dawn', 'Wrecking Crew', 'Picross DS',
       'Tactics Ogre: The Knight of Lodis', 'Fortune Street',
       'Mario & Wario', 'Pokemon Art Academy', 'Steel Diver',
       'Children of Mana', 'Mario Golf: World Tour', 'FlingSmash',
       'Bravely Second: End Layer', 'Densetsu no Stafi', 'Bomberman Hero',
       'Dance Dance Revolution: Mario Mix', 'Classic NES Series: Pac-Man',
       'Art Academy: Lessons for Everyone',
       'Mario & Sonic at the Rio 2016 Olympic Games', 'Mother 1+2',
       'Puzzle & Dragons Z + Super Mario Bros. Edition',
       'Samurai Warriors 3', 'Pokemon Puzzle League',
       'Mario Tennis Ultra Smash', 'Mario Golf: Advance Tour',
       'Densetsu no Stafi 2', 'Sin and Punishment: Star Successor',
       'Wario World', "Eternal Darkness: Sanity's Requiem",
       'Master of Illusion', 'Classic NES Series: Metroid',
       'Mischief Makers', 'Famicom Mini: Super Mario Bros. 2',
       'Dr. Mario 64', "Zack & Wiki: Quest for Barbaros' Treasure",
       'Animal Crossing: Amiibo Festival',
       'Ogre Battle 64: Person of Lordly Caliber', 'The Wonderful 101',
       'Mario no Super Picross', 'Story of Seasons',
       'Advance Wars: Dual Strike', 'Battalion Wars',
       'RR64: Ridge Racer 64', 'Mother 3', 'Wii Sports Club',
       'Fire Emblem: Fuuin no Tsurugi', 'Donkey Konga 2',
       'Mystery Case Files: The Malgrave Incident', 'Yoshi Touch & Go',
       'Custom Robo V2', 'Chibi-Robo! Plug into Adventure!',
       'Super Soccer', 'Wario Land II (GBC)', 'Elite Beat Agents',
       'Pokemon Channel', 'Custom Robo', 'Pac-Man World 2',
       'Trauma Center: Under the Knife', 'Hamtaro: Ham-Ham Heartbreak',
       "Kirby's Dream Land 3", 'Tetrisphere',
       'Trauma Center: Second Opinion', 'Picross 2', 'Battalion Wars 2',
       'Fossil Fighters: Frontier', 'Star Fox: Zero', 'Stunt Race FX',
       'Etrian Odyssey', 'Classic NES Series: Ice Climber',
       "Pandora's Tower", 'Planet Puzzle League',
       'Classic NES Series: Castlevania', 'Dr. Mario / Puzzle League',
       "Kirby's Block Ball", 'Doubutsu no Mori', 'KuruKuru Kururin',
       'Gameboy Gallery', 'Trauma Center: New Blood', 'NES Remix',
       'Rhythm Tengoku', 'Fossil Fighters (JP sales)',
       'Glory of Heracles', 'Trace Memory', 'Punch-Out!!',
       'The New Tetris', "Ken Griffey Jr.'s Slugfest", 'Just Dance Wii 2',
       'Battle & Get! Pokemon Typing DS', 'Tales of Phantasia',
       'Final Fantasy VI Advance', "Mega Man: Dr. Wily's Revenge",
       'Mega Man II', 'Sing Party', 'Pokemon Box: Ruby & Sapphire',
       'Donkey Kong GB: Dinky Kong & Dixie Kong',
       'ExciteBots: Trick Racing',
       'Moero! Nekketsu Rhythm Damashii: Osu! Tatakae! Ouendan! 2',
       'Baten Kaitos: Eternal Wings and the Lost Ocean',
       'Command & Conquer',
       'Tohoku Daigaku Karei Igaku Kenkyuusho - Kawashima Ryuuta Kyouju Kanshuu - Mono Sugoku Nou o Kitaeru 5-Funkan no Oni Training',
       'Magical Vacation', "America's Test Kitchen: Let's Get Cooking",
       'Fire Emblem: Shin Monshou no Nazo Hikari to Kage no Eiyuu',
       'DS Bungaku Zenshuu', 'Inazuma Eleven Strikers',
       'Final Fantasy V Advance', 'Polarium',
       'Classic NES Series: Bomberman', 'Fire Emblem: Thracia 776',
       'Metroid Prime Pinball', 'NBA Courtside 2 featuring Kobe Bryant',
       "Freshly-Picked: Tingle's Rosy Rupeeland", 'NBA Courtside 2002',
       'Classic NES Series: Excitebike', 'Classic NES Series: Xevious',
       'DK: King of Swing', 'Densetsu no Stafi 3', 'Chibi-Robo! Zip Lash',
       'Game & Wario', 'Nintendo Presents: Crossword Collection',
       'Girls Mode 3: Kirakira Code', 'Meteos',
       'Last Window: The Secret of Cape West',
       'Tetris 2 (weekly jp sales)', 'Naruto Shippuden: Ninja Council 4',
       'Super Swing Golf', 'Super R-Type', 'Tetris Attack',
       'Hamtaro: Ham-Ham Games', "Kirby's Star Stacker",
       'Shin Megami Tensei x Fire Emblem',
       "Disney's Magical Quest Starring Mickey and Minnie",
       'Spirit Camera: The Cursed Memoir', 'Yoshi Touch & Go (JP sales)',
       'Code Name: S.T.E.A.M.',
       'Are You Smarter Than a 5th Grader? Back to School',
       'Heroes of Ruin', 'Solatorobo: Red the Hunter',
       'Little Battlers eXperience: Baku Boost',
       'Trade & Battle: Card Hero', 'Tekken 3D: Prime Edition',
       'Ninja Gaiden 3', "Disney's Magical Mirror Starring Mickey Mouse",
       'Disney Magic World 2', 'Active Health with Carol Vorderman',
       'Sudoku Gridmaster (JP sales)', 'Daigasso! Band Brothers',
       'Face Training', 'Magical Starsign (US sales)', 'GameBoy Wars',
       'PokÃ©mon I Choose You / Squirtle Squad Game Boy Advance Video',
       'Daigasso! Band Brothers P', 'Sudoku Gridmaster',
       'PokÃ©mon Beach Blank-out Blastoise / Go West Young Meowth Game Boy Advance Video',
       'Custom Robo Arena', 'Densetsu no Stafi 4',
       'Street Fighter Alpha 2', 'Itoi Shigesato no Bass Tsuri No. 1',
       'Cubivore: Survival of the Fittest', 'True Swing Golf',
       'DS Rakubiki Jiten', 'Starcraft 64', 'F-Zero: GP Legend',
       'Culdcept', 'Geist', 'Okaeri! Chibi-Robo! Happy Richie Oosouji',
       'Doshin the Giant', 'Mr. Driller: Drill Spirits', 'Magnetica',
       'Kororinpa: Marble Mania', 'Illusion of Gaia',
       'Sin and Punishment',
       'PokÃ©mon: For Ho-Oh the Bells Toll!: Game Boy Advance Video',
       'Eyeshield 21: Max Devil Power', 'ASH: Archaic Sealed Heat',
       'Pocket Soccer League: Calciobit',
       'Fatal Frame: Maiden of Black Water', 'Zangeki no Reginleiv',
       'Kousoku Card Battle: Card Hero', 'Odama', 'Soma Bringer',
       'Famicom Mini: Famicom Tantei Club - Kieta Koukeisha Zenkouhen',
       'Irozuki Tingle no Koi no Balloon Trip', 'Picross 3D 2',
       'Dynasty Warriors Advance',
       'Mega Man Battle Network 5: Double Team DS (JP sales)',
       'Fatal Frame 2: Wii Edition',
       "Mickey's Speedway USA (weekly JP sales)",
       'Project Hacker: Kakusei', "L'Aigle de Guerre",
       'Nihon Keizai Shinbunsha Kanshuu: Shiranai Mamade wa Son o Suru Mono ya Okane no Shikumi DS',
       'Famicom Mini: Famicom Tantei Club Part II - Ushiro ni Tatsu Shoujo Zenkouhen',
       'Famicom Mini: Mappy', 'Touch Mechanic', 'Terranigma',
       'Brain Age: Concentration Training', 'Pokemon Rumble World',
       'Disney Art Academy', 'Inazuma Eleven 3',
       'Kurikin: Nano Island Story',
       'Tabi no Yubisashi Kaiwachou DS: DS Series 4 America',
       'Just Dance Wii U',
       'Famicom Mini: Famicom Mukashi Banashi - Shin Oniga Shima Zenkouhen',
       'Famicom Mini: Mario Bros.', 'Zero: Tsukihami no Kamen',
       'Famicom Mini: SD Gundam World Gachapon Senshi - Scramble Wars',
       'Famicom Mini: Star Soldier', 'Minna no Joushiki Ryoku TV',
       'Disaster: Day of Crisis',
       'Famicom Mini: Hikari Shinwa: Palutena no Kagami',
       'Mega Man Battle Network 5: Double Team DS (US sales)',
       'DS Uranai Seikatsu', 'Make 10: A Journey of Numbers',
       'Itoi Shigesato no Bass Tsuri No. 1 Ketteihan!',
       'Famicom Mini: Nazo no Murasame-Jou',
       'Famicom Mini: Wrecking Crew', 'Kanji Sonomama DS Rakubiki Jiten',
       'Another Code R: A Journey into Lost Memories',
       'Famicom Mini: Balloon Fight', 'Osu! Tatakae! Ouendan',
       'Mario vs. Donkey Kong: Tipping Stars', "Devil's Third",
       'Eigo de Tabisuru: Little Charo',
       'Tabi no Yubisashi Kaiwachou DS: DS Series 3 Kankoku',
       'Dance Dance Revolution: Mario Mix (JP sales)', 'Culdcept Revolt',
       'Mawashite Tsunageru Touch Panic',
       'Tabi no Yubisashi Kaiwachou DS: DS Series 2 Chuugoku',
       'QUIZ PARTY', 'Wii de Asobu Chibi-Robo!',
       'Tabi no Yubisashi Kaiwachou DS: DS Series 1 Thai',
       'Sekai no Gohan Shaberu! DS Oryouri Navi',

In [68]:
nint['Name']

0                                               Wii Sports
1                                        Super Mario Bros.
2                                           Mario Kart Wii
3                                        Wii Sports Resort
4                                 Pokemon Red/Pokemon Blue
                               ...
16269                             Slide Adventure: Mag Kid
16357                 Mario vs. Donkey Kong: Tipping Stars
16456                             Art Academy: Home Studio
16473                                      Captain Rainbow
16542    Mario & Luigi: Paper Jam & Mario Kart 7 Double...
Name: Name, Length: 703, dtype: object

## -Q3publisher with highest sale in  global

In [116]:
games.groupby(['Publisher'])['Global_Sales'].max().idxmax()

'Nintendo'

In [140]:
games.groupby(['Publisher'])['Global_Sales'].max().sort_values(ascending=False).idxmax()

'Nintendo'

## -Q4In which region the publisher nintendo has high sales

In [127]:
games

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [145]:
high=games.groupby(['Publisher'])

In [149]:
high=high.get_group('Nintendo')

C:\Users\hp\AppData\Local\Temp\ipykernel_716\2118574242.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  high=high.get_group('Nintendo')

In [151]:
high

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16269,16272,Slide Adventure: Mag Kid,DS,2007.0,Action,Nintendo,0.00,0.00,0.01,0.00,0.01
16357,16360,Mario vs. Donkey Kong: Tipping Stars,WiiU,2015.0,Puzzle,Nintendo,0.00,0.00,0.01,0.00,0.01
16456,16459,Art Academy: Home Studio,WiiU,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01
16473,16476,Captain Rainbow,Wii,2008.0,Adventure,Nintendo,0.00,0.00,0.01,0.00,0.01
16542,16545,Mario & Luigi: Paper Jam & Mario Kart 7 Double...,3DS,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01

In [159]:
high[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']].max()

NA_Sales       41.49
EU_Sales       29.02
JP_Sales       10.22
Other_Sales     8.46
dtype: float64

In [157]:
high[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']].max().idxmax()

'NA_Sales'

## -Q5Retrieve the game that has highest sale in 2010

In [187]:
games['Year']=games['Year'].astype('int64')

In [198]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16598 non-null  int64
 4   Genre         16598 non-null  object
 5   Publisher     16598 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 1.4+ MB

In [214]:
highgame=games.groupby(['Year'])

In [216]:
highgame

In [220]:
highgame=highgame.get_group(2010)
highgame

C:\Users\hp\AppData\Local\Temp\ipykernel_716\2972908449.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  highgame=highgame.get_group(2010)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
15,16,Kinect Adventures!,X360,2010,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
26,27,Pokemon Black/Pokemon White,DS,2010,Role-Playing,Nintendo,5.57,3.28,5.65,0.82,15.32
31,32,Call of Duty: Black Ops,X360,2010,Shooter,Activision,9.67,3.73,0.11,1.13,14.64
40,41,Call of Duty: Black Ops,PS3,2010,Shooter,Activision,5.98,4.44,0.48,1.83,12.73
54,55,Gran Turismo 5,PS3,2010,Racing,Sony Computer Entertainment,2.96,4.88,0.81,2.12,10.77
...,...,...,...,...,...,...,...,...,...,...,...
16437,16440,The Cages: Pro Style Batting Practice,Wii,2010,Sports,Konami Digital Entertainment,0.01,0.00,0.00,0.00,0.01
16478,16481,Ishin no Arashi: Shippuu Ryuumeden,DS,2010,Strategy,Tecmo Koei,0.00,0.00,0.01,0.00,0.01
16487,16490,Slotter Mania P: Tetsuya Shinjuku vs Ueno,PSP,2010,Misc,Dorart,0.00,0.00,0.01,0.00,0.01
16501,16504,"Transformers: War for Cybertron (XBox 360, PS3...",PC,2010,Shooter,Activision,0.01,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01

In [224]:
highgame=highgame.groupby(['Name'])

In [234]:
highgame[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']].max().idxmax()

NA_Sales                Kinect Adventures!
EU_Sales                Kinect Adventures!
JP_Sales       Pokemon Black/Pokemon White
Other_Sales                 Gran Turismo 5
dtype: object

In [236]:
highgame['Global_Sales'].max().idxmax()

'Kinect Adventures!'

## Q6Retrive the games name and publisher with genre is shooter

In [255]:
genre=games.groupby(['Genre'])

In [257]:
genre=genre.get_group('Shooter')
genre

C:\Users\hp\AppData\Local\Temp\ipykernel_716\220463387.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  genre=genre.get_group('Shooter')

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
9,10,Duck Hunt,NES,1984,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31
29,30,Call of Duty: Modern Warfare 3,X360,2011,Shooter,Activision,9.03,4.28,0.13,1.32,14.76
31,32,Call of Duty: Black Ops,X360,2010,Shooter,Activision,9.67,3.73,0.11,1.13,14.64
33,34,Call of Duty: Black Ops 3,PS4,2015,Shooter,Activision,5.77,5.81,0.35,2.31,14.24
34,35,Call of Duty: Black Ops II,PS3,2012,Shooter,Activision,4.99,5.88,0.65,2.52,14.03
...,...,...,...,...,...,...,...,...,...,...,...
16501,16504,"Transformers: War for Cybertron (XBox 360, PS3...",PC,2010,Shooter,Activision,0.01,0.00,0.00,0.00,0.01
16569,16572,Resident Evil 4 HD,XOne,2016,Shooter,Capcom,0.01,0.00,0.00,0.00,0.01
16577,16580,Damnation,PC,2009,Shooter,Codemasters,0.00,0.01,0.00,0.00,0.01
16585,16588,Breach,PC,2011,Shooter,Destineer,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01

In [261]:
genre[['Name','Publisher','Genre']]

                                                    Name    Publisher    Genre
9                                              Duck Hunt     Nintendo  Shooter
29                        Call of Duty: Modern Warfare 3   Activision  Shooter
31                               Call of Duty: Black Ops   Activision  Shooter
33                             Call of Duty: Black Ops 3   Activision  Shooter
34                            Call of Duty: Black Ops II   Activision  Shooter
...                                                  ...          ...      ...
16501  Transformers: War for Cybertron (XBox 360, PS3...   Activision  Shooter
16569                                 Resident Evil 4 HD       Capcom  Shooter
16577                                          Damnation  Codemasters  Shooter
16585                                             Breach    Destineer  Shooter
16594                      Men in Black II: Alien Escape   Infogrames  Shooter

[1310 rows x 3 columns]

## Q7List out the racing game that is published by Sony Computer Entertainment

In [280]:
race=games.groupby(['Genre'])

In [282]:
race=race.get_group('Racing')
race

C:\Users\hp\AppData\Local\Temp\ipykernel_716\3604274133.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  race=race.get_group('Racing')

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
11,12,Mario Kart DS,DS,2005,Racing,Nintendo,9.81,7.57,4.13,1.92,23.42
28,29,Gran Turismo 3: A-Spec,PS2,2001,Racing,Sony Computer Entertainment,6.85,5.09,1.87,1.16,14.98
42,43,Mario Kart 7,3DS,2011,Racing,Nintendo,4.74,3.91,2.67,0.89,12.21
47,48,Gran Turismo 4,PS2,2004,Racing,Sony Computer Entertainment,3.01,0.01,1.10,7.53,11.66
...,...,...,...,...,...,...,...,...,...,...,...
16530,16533,SÃ©bastien Loeb Rally Evo,XOne,2016,Racing,Milestone S.r.l,0.00,0.01,0.00,0.00,0.01
16543,16546,Driving Simulator 2011,PC,2011,Racing,0,0.00,0.01,0.00,0.00,0.01
16573,16576,Mini Desktop Racing,Wii,2007,Racing,Popcorn Arcade,0.01,0.00,0.00,0.00,0.01
16574,16577,Yattaman Wii: BikkuriDokkiri Machine de Mou Ra...,Wii,2008,Racing,Takara Tomy,0.00,0.00,0.01,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01

In [286]:
race[race['Publisher']=='Sony Computer Entertainment']

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
28,29,Gran Turismo 3: A-Spec,PS2,2001,Racing,Sony Computer Entertainment,6.85,5.09,1.87,1.16,14.98
47,48,Gran Turismo 4,PS2,2004,Racing,Sony Computer Entertainment,3.01,0.01,1.10,7.53,11.66
52,53,Gran Turismo,PS,1997,Racing,Sony Computer Entertainment,4.02,3.87,2.54,0.52,10.95
54,55,Gran Turismo 5,PS3,2010,Racing,Sony Computer Entertainment,2.96,4.88,0.81,2.12,10.77
69,70,Gran Turismo 2,PS,1999,Racing,Sony Computer Entertainment,3.88,3.42,1.69,0.50,9.49
...,...,...,...,...,...,...,...,...,...,...,...
12820,12822,MotoGP 4 - Official Game of MotoGP,PS2,2005,Racing,Sony Computer Entertainment,0.03,0.02,0.00,0.01,0.06
13002,13004,Ferrari F355 Challenge,PS2,2002,Racing,Sony Computer Entertainment,0.03,0.02,0.00,0.01,0.05
13893,13895,WRC: FIA World Rally Championship,PSP,2005,Racing,Sony Computer Entertainment,0.02,0.01,0.00,0.01,0.04
13997,13999,Formula 1 06,PS2,2006,Racing,Sony Computer Entertainment,0.00,0.00,0.04,0.00,0.04
14166,14168,MotoGP,PSP,2006,Racing,Sony Computer Entertainment,0.03,0.00,0.00,0.00,0.03

In [33]:
games

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

### Q8 retrieve the average of global sales of nintendo publishers

In [39]:
pub=games.groupby(['Publisher'])

In [47]:
pubgl=pub.get_group('Nintendo')
pubgl

C:\Users\hp\AppData\Local\Temp\ipykernel_10700\4100238662.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  pubgl=pub.get_group('Nintendo')

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16269,16272,Slide Adventure: Mag Kid,DS,2007.0,Action,Nintendo,0.00,0.00,0.01,0.00,0.01
16357,16360,Mario vs. Donkey Kong: Tipping Stars,WiiU,2015.0,Puzzle,Nintendo,0.00,0.00,0.01,0.00,0.01
16456,16459,Art Academy: Home Studio,WiiU,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01
16473,16476,Captain Rainbow,Wii,2008.0,Adventure,Nintendo,0.00,0.00,0.01,0.00,0.01
16542,16545,Mario & Luigi: Paper Jam & Mario Kart 7 Double...,3DS,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.00,0.01

In [53]:
pubgl['Global_Sales'].mean()

2.541337126600285

### Q9 retrieve the platform with highest globalsales

In [108]:
games.nlargest(1,'Global_Sales')

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74

### Q10 retrieve the details of the lowest globalsales in 2008

In [117]:
year=games.groupby(['Year'])

In [127]:
year_2008=year.get_group(2008)
year_2008

C:\Users\hp\AppData\Local\Temp\ipykernel_10700\728377944.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  year_2008=year.get_group(2008)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
39,40,Super Smash Bros. Brawl,Wii,2008.0,Fighting,Nintendo,6.75,2.61,2.66,1.02,13.04
51,52,Grand Theft Auto IV,X360,2008.0,Action,Take-Two Interactive,6.76,3.10,0.14,1.03,11.02
56,57,Grand Theft Auto IV,PS3,2008.0,Action,Take-Two Interactive,4.76,3.76,0.44,1.62,10.57
88,89,PokÃ©mon Platinum Version,DS,2008.0,Role-Playing,Nintendo,2.82,1.78,2.69,0.55,7.84
...,...,...,...,...,...,...,...,...,...,...,...
16575,16578,Neo Angelique Special,PSP,2008.0,Adventure,Tecmo Koei,0.00,0.00,0.01,0.00,0.01
16580,16583,Real Rode,PS2,2008.0,Adventure,Kadokawa Shoten,0.00,0.00,0.01,0.00,0.01
16588,16591,Mega Brain Boost,DS,2008.0,Puzzle,Majesco Entertainment,0.01,0.00,0.00,0.00,0.01
16592,16595,Plushees,DS,2008.0,Simulation,Destineer,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01

In [129]:
year_2008.nsmallest(1,"Global_Sales")

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
15980,15983,Turok,PC,2008.0,Action,Touchstone,0.0,0.01,0.0,0.0,0.01

## Q11 retrieve the highest globalsales year which genre comes under action

In [132]:
genr=games.groupby(['Genre'])

In [138]:
gen=genr.get_group('Action')
gen

C:\Users\hp\AppData\Local\Temp\ipykernel_10700\2741153656.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  gen=genr.get_group('Action')

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
17,18,Grand Theft Auto: San Andreas,PS2,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81
23,24,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
24,25,Grand Theft Auto: Vice City,PS2,2002.0,Action,Take-Two Interactive,8.41,5.49,0.47,1.78,16.15
38,39,Grand Theft Auto III,PS2,2001.0,Action,Take-Two Interactive,6.99,4.51,0.30,1.30,13.10
...,...,...,...,...,...,...,...,...,...,...,...
16564,16567,Original Frisbee Disc Sports: Ultimate & Golf,DS,2007.0,Action,"Destination Software, Inc",0.01,0.00,0.00,0.00,0.01
16567,16570,Fujiko F. Fujio Characters: Great Assembly! Sl...,3DS,2014.0,Action,Namco Bandai Games,0.00,0.00,0.01,0.00,0.01
16582,16585,Planet Monsters,GBA,2001.0,Action,Titus,0.01,0.00,0.00,0.00,0.01
16583,16586,Carmageddon 64,N64,1999.0,Action,Virgin Interactive,0.01,0.00,0.00,0.00,0.01
16589,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016.0,Action,dramatic create,0.00,0.00,0.01,0.00,0.01

In [144]:
gen.nlargest(1,'Global_Sales')

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.4

In [146]:
gen.nlargest(1,'Global_Sales')['Year']

16    2013.0
Name: Year, dtype: float64

### Q12 retrieve the games that comes under the platform 'PS3'

In [150]:
plat=games.groupby(['Platform'])

In [156]:
plat.get_group('PS3')

C:\Users\hp\AppData\Local\Temp\ipykernel_10700\3514334872.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  plat.get_group('PS3')

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
34,35,Call of Duty: Black Ops II,PS3,2012.0,Shooter,Activision,4.99,5.88,0.65,2.52,14.03
37,38,Call of Duty: Modern Warfare 3,PS3,2011.0,Shooter,Activision,5.54,5.82,0.49,1.62,13.46
40,41,Call of Duty: Black Ops,PS3,2010.0,Shooter,Activision,5.98,4.44,0.48,1.83,12.73
54,55,Gran Turismo 5,PS3,2010.0,Racing,Sony Computer Entertainment,2.96,4.88,0.81,2.12,10.77
...,...,...,...,...,...,...,...,...,...,...,...
16450,16453,Hyperdimension Neptunia mk2,PS3,2011.0,Action,Nippon Ichi Software,0.00,0.01,0.00,0.00,0.01
16451,16454,Shin Koihime Musou: Otome Taisen * Sangokushi ...,PS3,2014.0,Adventure,Views,0.00,0.00,0.01,0.00,0.01
16480,16483,Muv-Luv Alternative,PS3,2012.0,Simulation,5pb,0.00,0.00,0.01,0.00,0.01
16521,16524,Akatsuki no Goei Trinity,PS3,2012.0,Adventure,5pb,0.00,0.00,0.01,0.00,0.01
16541,16544,Battle Fantasia,PS3,2008.0,Fighting,505 Games,0.00,0.00,0.01,0.00,0.01

In [158]:
plat.get_group('PS3')['Name']

C:\Users\hp\AppData\Local\Temp\ipykernel_10700\2329390583.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  plat.get_group('PS3')['Name']

16                                      Grand Theft Auto V
34                              Call of Duty: Black Ops II
37                          Call of Duty: Modern Warfare 3
40                                 Call of Duty: Black Ops
54                                          Gran Turismo 5
                               ...
16450                          Hyperdimension Neptunia mk2
16451    Shin Koihime Musou: Otome Taisen * Sangokushi ...
16480                                  Muv-Luv Alternative
16521                             Akatsuki no Goei Trinity
16541                                      Battle Fantasia
Name: Name, Length: 1329, dtype: object

## Q13 retrive the gamename with globalsales=20.81

In [169]:
games[games['Global_Sales']==20.81]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
17,18,Grand Theft Auto: San Andreas,PS2,2004.0,Action,Take-Two Interactive,9.43,0.4,0.41,10.57,20.81

In [171]:
games[games['Global_Sales']==20.81]['Name']

17    Grand Theft Auto: San Andreas
Name: Name, dtype: object

## Q14 list out the publishers in 2009

In [178]:
games[games['Year']==2009]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
14,15,Wii Fit Plus,Wii,2009.0,Sports,Nintendo,9.09,8.59,2.53,1.79,22.00
36,37,Call of Duty: Modern Warfare 2,X360,2009.0,Shooter,Activision,8.52,3.63,0.08,1.29,13.51
45,46,Pokemon HeartGold/Pokemon SoulSilver,DS,2009.0,Action,Nintendo,4.40,2.77,3.96,0.77,11.90
...,...,...,...,...,...,...,...,...,...,...,...
16540,16543,15 Days,PC,2009.0,Adventure,DTP Entertainment,0.00,0.01,0.00,0.00,0.01
16551,16554,Sweet Honey Coming,PS2,2009.0,Adventure,Kadokawa Shoten,0.00,0.00,0.01,0.00,0.01
16577,16580,Damnation,PC,2009.0,Shooter,Codemasters,0.00,0.01,0.00,0.00,0.01
16586,16589,Secret Files 2: Puritas Cordis,DS,2009.0,Adventure,Deep Silver,0.00,0.01,0.00,0.00,0.01
16587,16590,Mezase!! Tsuri Master DS,DS,2009.0,Sports,Hudson Soft,0.00,0.00,0.01,0.00,0.01

In [180]:
games[games['Year']==2009]['Publisher']

3                 Nintendo
8                 Nintendo
14                Nintendo
36              Activision
45                Nintendo
               ...
16540    DTP Entertainment
16551      Kadokawa Shoten
16577          Codemasters
16586          Deep Silver
16587          Hudson Soft
Name: Publisher, Length: 1431, dtype: object

## Q15 list out the highest ranked publisher at 2006

In [189]:
games[games['Year']==2006].head(1)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74

In [193]:
games[games['Year']==2006].head(1)['Publisher']

0    Nintendo
Name: Publisher, dtype: object